[package]
name = "wspace-syntax"
version = "0.1.0"
authors = ["Thalia Archibald <thalia@archibald.dev>"]
edition = "2021"
description = "Parsing and syntax trees for the Whitespace programming language and its various syntaxes"
repository = "https://github.com/thaliaarchi/wspace-syntax"
license = "MPL-2.0"
keywords = ["whitespace", "syntax", "parsing"]
categories = ["parser-implementations"]

[dependencies]
aho-corasick = "1.0"
bitvec = "1.0"
memchr = "2.5"
phf = { version = "0.11", features = ["macros", "uncased"] }
rug = "1.19"
uncased = "0.9"
unicode-ident = "1.0"

[patch.crates-io]
# Waiting on rust-phf/rust-phf#289
phf = { git = "https://github.com/thaliaarchi/rust-phf" }
