[workspace.package]
authors = ["Thalia Archibald <thalia@archibald.dev>"]
edition = "2021"
repository = "https://github.com/thaliaarchi/lazy-wspace"
license = "MPL-2.0"

[workspace]
members = [
  "lazy-wspace",
  "lazy-wspace-generate",
  "lazy-wspace-macros",
  "wspace-syntax",
  "wspace-syntax-test",
]

[patch.crates-io]
# Waiting on rust-phf/rust-phf#289
phf = { git = "https://github.com/thaliaarchi/rust-phf" }

[profile.release]
lto = true
