[package]
name = "lazy-wspace"
version = "0.1.0"
authors = ["Thalia Archibald"]
edition = "2021"
description = "A Whitespace interpreter with lazy semantics"
repository = "https://github.com/thaliaarchi/lazy-wspace"
license = "GPL-3.0-or-later"
keywords = ["whitespace", "interpreter"]
categories = ["compilers"]

[dependencies]
bitvec = "1.0"
rug = "1.19"

[profile.release]
lto = true
