[package]
name = "wspace-syntax"
version = "0.1.0"
authors = ["Thalia Archibald <thalia@archibald.dev>"]
edition = "2021"
description = "Parsing and syntax trees for the Whitespace programming language and its various syntaxes"
repository = "https://github.com/thaliaarchi/wspace-syntax"
license = "MPL-2.0"
keywords = ["whitespace", "syntax", "parsing"]
categories = ["parser-implementations"]

[dependencies]
aho-corasick = "1.0"
bitvec = "1.0"
memchr = "2.5"
rug = "1.19"
unicode-ident = "1.0"
