[workspace.package]
authors = ["Thalia Archibald <thalia@archibald.dev>"]
edition = "2021"
repository = "https://github.com/thaliaarchi/wspace-syntax"
license = "MPL-2.0"

[workspace]
members = [
  "wspace-syntax",
  "wspace-syntax-test",
]

[patch.crates-io]
# Waiting on rust-phf/rust-phf#289
phf = { git = "https://github.com/thaliaarchi/rust-phf" }
