edition = "2021"
newline_style = "Unix"

## Nightly options
# comment_width = 80
# format_code_in_doc_comments = true
# format_macro_matchers = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# wrap_comments = true
